version: '3.7'
services:
    postgres:
        build: ./database
        environment:
            POSTGRES_DB: galanonim
            POSTGRES_USER: galanonimuser
            POSTGRES_PASSWORD: galanonimpassword
        volumes:
            - data:/var/lib/postgresql/data
        networks: 
            - default
    redis:
        image: redis:alpine  
        networks: 
            - default 
    server:
        build:
            context: ./server
            dockerfile: Dockerfile
        ports: 
            - "8888:8888"
        depends_on: 
            - postgres
            - redis
        networks: 
            - default
volumes:
    data:
