server:
  host: "127.0.0.1"
  port: "8888"
  mode: "default"
database:
  host: "database"
  port: "5432"  
  name: "galanonim"
  user: "galanonimuser"
  password: "galanonimpassword"
jwt:
  tokenSecret: "someTokenSecretJWT"
  expTime: 1
  issuer: "galanonim"